name: 'Confluent cp-all-in-one for Apache Kafka'
description: 'Setup Confluent cp-all-in-one'
author: 'ybyzek'
inputs:
  github branch version:
    description: 'GitHub branch of cp-all-in-one to use'
    required: false
    default: 'latest'
  service:
    description: 'Define service up to which to start'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
