{
 "title": "Authentication Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Kafka Rest Producer/Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_rest_producer_metrics_outgoing_byte_rate",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_rest_consumer_metrics_incoming_byte_rate",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overall Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Auth Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_confluent_common_security_jetty_auth_oauth_successful_auth_latency_avg{job=\"prometheus\"}",
     "legendFormat": "OAuth Average Latency"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_mtls_successful_auth_latency_avg{job=\"prometheus\"}",
     "legendFormat": "MTLS Average Latency"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_mds_oauth_successful_auth_latency_avg{job=\"prometheus\"}",
     "legendFormat": "MDS Auth Average Latency"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_basic_successful_auth_latency_avg{job=\"prometheus\"}",
     "legendFormat": "Basic Average Latency"
    }
   ]
  },
  { "title": "Overall Auth Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Auth Request Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_confluent_common_security_jetty_auth_basic_successful_auth_count{job=\"prometheus\"}",
     "legendFormat": "Basic Auth Count"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_mds_oauth_successful_auth_count{job=\"prometheus\"}",
     "legendFormat": "MDS Auth Count"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_mtls_successful_auth_count{job=\"prometheus\"}",
     "legendFormat": "MTLS Auth Count"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_oauth_successful_auth_count{job=\"prometheus\"}",
     "legendFormat": "Oauth Auth Count"
    }
   ]
  },
  {
   "title": "Authentication Success Precision Percentage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_confluent_common_security_jetty_auth_oauth_successful_auth_count{job=\"prometheus\"} * 100/(io_confluent_common_security_jetty_auth_oauth_successful_auth_count{job=\"prometheus\"}+io_confluent_common_security_jetty_auth_oauth_unsuccessful_auth_count{job=\"prometheus\"})",
     "legendFormat": "OAuth"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_mtls_successful_auth_count{job=\"prometheus\"} * 100/(io_confluent_common_security_jetty_auth_mtls_successful_auth_count{job=\"prometheus\"}+io_confluent_common_security_jetty_auth_mtls_unsuccessful_auth_count{job=\"prometheus\"})",
     "legendFormat": "Mtls"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_mds_oauth_successful_auth_count{job=\"prometheus\"} * 100/(io_confluent_common_security_jetty_auth_mds_oauth_successful_auth_count{job=\"prometheus\"}+io_confluent_common_security_jetty_auth_mds_oauth_unsuccessful_auth_count{job=\"prometheus\"})",
     "legendFormat": "MDS OAuth"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_basic_successful_auth_count{job=\"prometheus\"} * 100/(io_confluent_common_security_jetty_auth_basic_successful_auth_count{job=\"prometheus\"}+io_confluent_common_security_jetty_auth_basic_unsuccessful_auth_count{job=\"prometheus\"})",
     "legendFormat": "Basic"
    }
   ]
  },
  { "title": "OAuth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "OAuth latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "io_confluent_common_security_jetty_auth_oauth_successful_auth_latency{job=\"prometheus\"}",
     "legendFormat": "Latency"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_oauth_successful_auth_latency_avg{job=\"prometheus\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_oauth_successful_auth_latency_95{job=\"prometheus\"}",
     "legendFormat": "95 Percentile Latency"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_oauth_successful_auth_latency_99{job=\"prometheus\"}",
     "legendFormat": "99 Percentile Latency"
    },
    {
     "expr": "io_confluent_common_security_jetty_auth_oauth_successful_auth_latency_max{job=\"prometheus\"}",
     "legendFormat": "Max Latency"
    }
   ]
  }
 ]
}