#!/usr/bin/env bash

. /etc/confluent/docker/bash-config

echo "===> User"
id

echo "===> Configuring ..."
/etc/confluent/docker/configure

echo "===> Launching ... "
exec /etc/confluent/docker/launch