CREATE TABLE C##MYUSER.foo 
(
   "_id"          integer,
   "SomeColumn"  varchar(100)
) tablespace sysaux;



insert into C##MYUSER.foo ('_id', "SomeColumn") values (1,'Bob');

select * from C##MYUSER.foo 


kafka-topics --create --topic redo-log-topic \
--bootstrap-server broker:9092 --replication-factor 1 \
--partitions 1 --config cleanup.policy=delete \
--config retention.ms=120960000


kafka-topics --create --topic SimpleOracleCDC-ORCLCDB-redo-log \
--bootstrap-server broker:9092 --replication-factor 1 \
--partitions 1 --config cleanup.policy=delete \
--config retention.ms=120960000



CREATE TABLE C##MYUSER.emp
(
    "_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    lastname VARCHAR2(100),
    PRIMARY KEY ("_id")
) tablespace sysaux;

insert into C##MYUSER.emp (name, lastname) values ('Bob', 'Perez');
insert into C##MYUSER.emp (name, lastname) values ('Jane','Revuelta');
insert into C##MYUSER.emp (name, lastname) values ('Mary','Kristmas');
insert into C##MYUSER.emp (name, lastname) values ('Alice','Cambio');



SHOW PDBS

insert into C##MYUSER.emp (name, lastname) values ('Paul','nuevo');
insert into C##MYUSER.emp (name, lastname) values ('newName','ksqldb43');

DELETE FROM C##MYUSER.emp WHERE I=5;


update C##MYUSER.emp
set lastname='SOTO'
where I=1;


CREATE STREAM ORACLE (
    I BIGINT,
    NAME VARCHAR,
    LASTNAME VARCHAR,
    op_type VARCHAR
  ) WITH (
    KAFKA_TOPIC = 'ORCLCDB-EMP',
    VALUE_FORMAT = 'AVRO'
  );
///este es el bueno

  CREATE STREAM CDCORACLE (I DECIMAL(20,0), NAME varchar, LASTNAME varchar, op_type VARCHAR) WITH
    (kafka_topic='ORCLCDB-EMP', value_format='AVRO');

  CREATE STREAM pageviews_reduced_2 ( NAME VARCHAR)
  WITH (KAFKA_TOPIC='ORCLCDB-EMP',
        VALUE_FORMAT='AVRO');

  select * from PAGEVIEWS_ORIGINAL333XX where OP_TYPE!='D' EMIT CHANGES;

  select CAST(I AS BIGINT) as "_id",  AS_VALUE(I) AS ID2, NAME ,  LASTNAME , OP_TYPE  from CDCORACLE WHERE OP_TYPE!='D' EMIT CHANGES;


  CREATE STREAM WRITEOP AS
  SELECT CAST(I AS BIGINT) as "_id",  NAME ,  LASTNAME , OP_TYPE  from CDCORACLE WHERE OP_TYPE!='D' EMIT CHANGES;
//CSAS_DELETEOP_5

CREATE STREAM DELETEOP AS
  SELECT CAST(I AS BIGINT) as "_id",  NAME ,  LASTNAME , OP_TYPE  from CDCORACLE WHERE OP_TYPE='D' EMIT CHANGES;

  CREATE STREAM WRITEOP4 AS
  SELECT I ,CAST(I AS BIGINT) AS ID2,  NAME ,  LASTNAME , OP_TYPE  from CDCORACLE WHERE OP_TYPE!='D' EMIT CHANGES;



UPDATE C##MYUSER.emp
SET LASTNAME = 'ksqldb43'
WHERE NAME = 'Juan';


CREATE STREAM CDCORACLE3 (I DECIMAL(20,0), NAME varchar, LASTNAME varchar, op_type VARCHAR) WITH
    (kafka_topic='ORCLCDB-EMP', value_format='AVRO', key_format='NONE');


CREATE STREAM WRITEOP3 AS
  SELECT CAST(I AS BIGINT) as "_id",  NAME ,  LASTNAME , OP_TYPE  from CDCORACLE3 WHERE OP_TYPE!='D' EMIT CHANGES;

